### ISSUE TITLE
调用本地api进行评测有时会出现404错误

### ISSUE THREAD

**Issue by YYLCyylc** [THUDM/AlignBench#13]
用本地qwen-chat-14b生成jsonl数据后用本地的qwen-chat-72b尝试评测，执行过程中提示返回的json为404
![image](https://github.com/THUDM/AlignBench/assets/50295520/c02f1fb9-bb8e-4c70-a0be-0f2e1b5cedca)
查看72b后台，感觉是输出过长，超过1min导致触发超时
![image](https://github.com/THUDM/AlignBench/assets/50295520/c7af1596-cd9d-461d-bae1-471c8b4647dc)
但是本地输入同样的prompt进行尝试，10s内就出了结果，这是为什么
![image](https://github.com/THUDM/AlignBench/assets/50295520/8ac8357e-6fc8-4a7c-853b-e4aa6d348cef)

**Comment by FoolMark** [comment]
请问你是咋解决的，我传上去也是这样

**Comment by FoolMark** [comment]
我这边是报request长度过长

**Comment by Xiao9905** [comment]
@YYLCyylc 你好，

由于你使用的是本地的测评模型，具体情况我们就不太了解了，不过可能的原因包括并发数过大、使用非流式生成导致超时等。
