### ISSUE TITLE
网站上传测评 failed

### ISSUE THREAD

**Issue by FoolMark** [THUDM/AlignBench#14]
报错信息:
<html>
 <head><title>413 Request Entity Too Large</title></head>
 <body>
 <center><h1>413 Request Entity Too Large</h1></center>
 <hr><center>nginx/1.18.0 (Ubuntu)</center>
 </body>
 </html>

是生成的太长了吗，csv文件整个是1m大小

**Comment by Xiao9905** [comment]
@FoolMark 你好，

网站已调整最大上传大小为10M，可以再尝试下。
