### ISSUE TITLE
无法注册和登录：注册页面弹出红叉，用其他账号登录，填好基本信息后，按登录按钮无反应

### ISSUE THREAD

**Issue by Xlee9403** [THUDM/AlignBench#16]
![lADPKE0U6vUm7MfMzM0BwQ_449_204](https://github.com/THUDM/AlignBench/assets/30120322/812e7396-fc49-4f1c-bf8f-271e81ce8a50)

**Comment by Xiao9905** [comment]
@Xlee9403 你好，

网站昨天正在进行更新修复，现在应该已经恢复。麻烦重新尝试一下～

**Comment by MoYJiang** [comment]
无法注册，会弹出小红叉。

**Comment by Xlee9403** [comment]
> @Xlee9403 你好，
> 
> 网站昨天正在进行更新修复，现在应该已经恢复。麻烦重新尝试一下～

可以注册登录了，谢谢~
