### ISSUE TITLE
有评测Qwen72B模型吗？

### ISSUE THREAD

**Issue by wen2cheng** [THUDM/AlignBench#4]

**Comment by xianghuisun** [comment]
+1

**Comment by leixy20** [comment]
感谢您对 AlignBench 的关注！
我们暂时还没有评测 Qwen-72B 模型，我们注意到 Qwen-14B 模型表现很好，所以我们也对 Qwen-72B 的表现很感兴趣，我们之后也会引入更多模型进入评测。

**Comment by FoolMark** [comment]
我测出来是6.12，感觉挺高的，供参考
