### ISSUE TITLE
大佬们，这个评测模型会开源吗？

### ISSUE THREAD

**Issue by cos0sin0** [THUDM/AlignBench#5]

**Comment by Xiao9905** [comment]
@cos0sin0 你好，

评测模型后续会有部分相关数据和代码的开源，具体可以在github.com/thu-coai/CritqiueLLM仓库下进行咨询～

**Comment by kkTea** [comment]
> @cos0sin0 你好，
> 
> 评测模型后续会有部分相关数据和代码的开源，具体可以在github.com/thu-coai/CritqiueLLM仓库下进行咨询～

大佬，仓库404找不到了
