### ISSUE TITLE
请问，官网给的example.csv文件，打开乱码无法查看格式

### ISSUE THREAD

**Issue by White-Friday** [THUDM/AlignBench#6]
url: https://llmbench.ai/align/submit
1. 首先提前准备683个评测问题（resourse: https://github.com/THUDM/AlignBench/tree/master/data）的评测答案，并存储入文件中，请使用csv格式（683行1列）进行存储，[样例](https://llmbench.ai/image/align/example.csv)

乱码内容：

擃?飢蝞∪?擃?典??舐?靚v找????喳?蝪抒恣???折虜銝慟?哨????唾????批?銝慷?准? |  
-- | --
2006撟????伐??其??????脩洵33頧格?韏葉摰??? |   |   |   |   |   |   |  
撗拚?蟡? |   |   |   |   |   |   |   |   |   |   |  
蝵摩?嗽瑕孕?祆絲暺?Robert   Oppenheimer嚗◤隤蛹??摮撕銋??隞1941撟游??蛹蝢蝘郎?ａ憯怒?
?蛹?輯羲?其??典僑頧餌??嗅蝏銝剖?腺?單?韏?鋡急蝻蛹銝剖??銝??銝??嗡蜓?閬??輯羲?其?頨急銝剖?賣??箸?嚗蛹隞?頨怠?????嚗??株?葉?賢?嚗??舫?樴??迨????
?帕撠2014-15韏迤?瑕?隞?蝚砌?銝芣洹瘣脤??游??? |   |   |   |   |   |   |  
4KMnO4 +   6NaHSO3 = 4MnO2??+ 3Na2SO4 + 2K2SO4 + H2SO4 + 2H2O |   |   |   |   |   |  
銝?暻血隡西??函????嗆瓷?蝙?典?貌?交???蝥砍漲?漲?脖憐?舐??芾???湔1519撟氯?522撟湛??剖?隞芰????曹??典?繚?▼?嚗?憿輻??箇??園??643撟????伐??隞亙?暻血隡西銵??園?剖?隞芸??芾◤??嚗蝙?典?貌?臭??航M??

默认下载是csv文件，我把后缀改为html之后，就可以查看了，但是无格式，请问是否是上传错误了呢

**Comment by leixy20** [comment]
您好，很抱歉造成的困扰！
经过我们排查，应该是编码问题，问题来源是使用 python encoding="utf-8" 编码生成的 csv 文件头中不含 BOM 编码信息，所以在用一些默认编码不是 utf-8 的软件打开时会出现乱码。使用记事本或者 numbers.app 打开不会出现乱码。所以，一个快速的解决方案是用记事本打开然后用合适的编码重新另存为文件。
我们官网上的文件现在已经更新，在文件头中加入了 BOM 信息，所以应该可以正常打开，您可以重新下载查看。官网说明中的 python 代码已经改为 encoding='utf-8-sig' 应该可以解决这个问题。

**Comment by White-Friday** [comment]
请问，官网的评测模型是基于咱们自己的还是GPT4-0613的

**Comment by leixy20** [comment]
官网的评测模型是自己开发的 CritiqueLLM，目前暂时不支持多维度的评测，只给出分析和总分
