### ISSUE TITLE
有些题目的答案有待商榷

### ISSUE THREAD

**Issue by Triang-jyed-driung** [THUDM/AlignBench#7]
我先说一些数学

125：用自然数基数理论证明(a-b)c＝ac-bc
此题表述不清，因为自然数和基数理论是两个不同的东西。我认为一个合理的表述为：
在基于ZFC公理的基数理论中，设a,b,c为三个基数，且b≤a，证明(a-b)c＝ac-bc。
原题解答基本正确，但有需要改进的地方，因为构造(a-b)可能需要选择公理。

128：圆上任取3点构成一个三角形，该三角形包含圆心的概率是多少
这题主要问题在于概率测度是如何定义的，其实条件并不是很清楚，一定要说明，在圆周上均匀地选取，那么答案为1/4。

158：若集合A＝{x|kx²＋4x＋4＝0，x∈R}只有一个元素，则实数k的值为(　　) A.0 B.1 C.2 D.3
显然k=0和k=1都是正确答案，因为并没有指定该方程是二次方程。答案错误。

171：函数在闭区间连续如何推出有界
这题是Weierstrass定理的推论，但是参考答案真的不像是可以称得上一个“证明”。

178：m个n-1维超平面可以将n维空间分成多少份
这是一个经典的问题，参见Whitney数 https://oeis.org/A004070 ，答案为W(n,m)。对于模型而言，这应该是百科知识题而非数学题。因此答案错误。

212：帮我计算矩阵 \\n[0 1 -0 \\n0 0 1\\n-0.24 0.22 0.9]的特征值并给出latex格式的计算过程
题目的换行格式比较奇怪，并且在0前面加了不必要的负号。
如果计算矩阵[0 1 0; 0 0 1; -0.24 0.22 0.9]的特征值，特征根方程为x^3 -0.9x^2 -0.22x +0.24 =0, 三个特征值分别是 0.8, 0.6, -0.5。答案错误。

再说一个化学

7. 书写高锰酸钾和亚硫酸氢钠反应生成二氧化锰反应方程式
这个应该离子方程式比较恰当，反应条件是在水溶液中，并且是弱酸性，2MnO4- + 3HSO3- = 2MnO2↓ + 3SO4(2-) + H+ + H2O
如果亚硫酸氢钠过量，HSO3- 和 H+ 继续反应，那就是 2MnO4- + 4HSO3- = 2MnO2↓ + 3SO4(2-) + SO2↑ + 2H2O

**Comment by leixy20** [comment]
您好，感谢您的反馈！
这些题目参考答案的核查是由标注人员进行的，部分题目需要较强的专业知识，很抱歉出现一些问题，我们会根据您的反馈尽快核查和更新题目
