### ISSUE TITLE
提交成功后下载的得分和详细结果都是空的文件

### ISSUE THREAD

**Issue by HalcyonLiang** [THUDM/AlignBench#8]
e.g. 提交id : 657a7419477c2cb37c306f24
如果有提交错误的话，能辛苦透出错误信息嘛？

**Comment by Sanster** [comment]
我也遇到了这个问题，下载下来的score文件内容为：

<img width="794" alt="image" src="https://github.com/THUDM/AlignBench/assets/3998421/9c53b63f-7621-4aa1-99b8-45f6edaf6f8a">

**Comment by HalcyonLiang** [comment]
> 我也遇到了这个问题，下载下来的score文件内容为：
> 
> <img alt="image" width="794" src="https://private-user-images.githubusercontent.com/3998421/290458527-9c53b63f-7621-4aa1-99b8-45f6edaf6f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDQ4MjQsIm5iZiI6MTcwMjU0NDUyNCwicGF0aCI6Ii8zOTk4NDIxLzI5MDQ1ODUyNy05YzUzYjYzZi03NjIxLTRhYTEtOTliOC00NWY2ZWRhZjZmOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDkwMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU3YzViZGYwOTIwZTA4OGQ2ZGNiODk4NzQxMzc1Y2NjYzI0NDM5YzNlODJiNDk4MzA3YzAxZmRhMDNmNWIxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SuJszsfyywud7pxMGvHZ4a9tkaB74wcqe2VhNFG04nk">

cc 大佬，这个只是跑的慢...等出结果了，重新下载会有新的的 close了。
