### ISSUE TITLE
无法提交新结果

### ISSUE THREAD

**Issue by haochen2115** [THUDM/AlignBench#9]
cannot post https://llmbench.ai/api/v1/alignbench/upload 401'
![image](https://github.com/THUDM/AlignBench/assets/32786857/cf70a9d0-de90-41be-840b-6d9711f29385)

**Comment by Xiao9905** [comment]
@haochen2115 您好，

这个问题网站后端修复了，麻烦重新登陆提交一下看是否正常。感谢您对AlignBench的尝试。
